import type { Metadata } from "next";
import "./globals.css";
import { MantineProvider } from '@mantine/core';
import Navbar from "@/components/Header/Navbar";
import Footer from "@/components/Footer/Footer";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MantineProvider>
         <Navbar/>
        {children}
        <Footer/>
        </MantineProvider>
      </body>
    </html>
  );
}
